#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "rich"

[ui]
# Default command when jj is run without arguments
default-command = "log"
# Always use color
color = "auto"

[git]
# Push all bookmarks by default
push-all-bookmarks = false
