[diff]
pager = "delta"

[merge]
command = "vimdiff"

[git]
autoCommit = true
autoPush = false

[update]
command = "git"
args = ["pull", "--autostash", "--rebase", "origin", "master"]

[cd]
command = "zsh"
